# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
    identifier = "mastodon"
    name       = "Mastodon"
    url        = "https://douchi.space/@jojoriya"

    [social.params]
        icon = "brand-mastodon"

[[social]]
    identifier = "instagram"
    name       = "Instagram"
    url        = "https://www.instagram.com/jojoriya/"

    [social.params]
        icon = "brand-instagram"
