# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon        = "img/favicon.png"

# Accepted values: "default", "lastmod"
# default = see https://gohugo.io/quick-reference/glossary/#default-sort-order
# lastmod = sort by last modified date, in descending order
SortBy              = "default"

[footer]
    since      = 2026
    customText = "Powered by my ADHD & ASD"

[dateFormat]
    published   = ":date_full"
    lastUpdated = ":date_full"

[sidebar]
    emoji    = "ğŸª"
    subtitle = "éšæ€§æ¸¸èµ°."
    avatar   = "img/appleavatar.png"

[article]
    headingAnchor = false
    math          = false
    toc           = true
    readingTime   = true

    [article.license]
        enabled = true
        default = "ç‰ˆæƒæ‰€æœ‰ï¼Œç¦æ­¢è½¬è½½ã€‚è½¬å‘éœ€æ³¨æ˜æ–‡ç« é“¾æ¥ã€‚"

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

[opengraph.twitter]
    site = ""
    card = "summary_large_image"

[colorScheme]
    toggle  = true
    default = "auto"

## Comments
[comments]
    enabled  = true
    provider = "twikoo"

    # See all the available configurations at https://github.com/CaiJimmy/hugo-theme-stack/blob/master/config/_default/params.toml
    # Copy the configurations you need from there and paste it here.
     [comments.twikoo]
        envId = "https://twikoo-joeyrichles-projects.vercel.app/"
        region = ""
        path = ""
        lang = ""